"""empty message

Revision ID: 66cd11c08864
Revises: 57026e32a958
Create Date: 2016-10-27 17:32:56.046715

"""

# revision identifiers, used by Alembic.
revision = '66cd11c08864'
down_revision = '57026e32a958'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_constraint('articles_titile_key', 'articles', type_='unique')
    op.create_unique_constraint(None, 'articles', ['title'])
    op.drop_column('articles', 'titile')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('titile', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='unique')
    op.create_unique_constraint('articles_titile_key', 'articles', ['titile'])
    op.drop_column('articles', 'title')
    ### end Alembic commands ###
